# NOTE: This file is auto-generated by data-raw/generate_wrappers.R
# Do not edit by hand; re-run the generator instead.

#' BLCA_BCAN_HCRN BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
BLCA_BCAN_HCRN <- function(what = c("se", "expr", "meta")) {
  beacon_load("BLCA_BCAN_HCRN", what = what)
}

#' BLCA_BCAN_HCRN_DisTypeMIBC_NodalNo_Metunknown_SampSourceunknown BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
BLCA_BCAN_HCRN_DisTypeMIBC_NodalNo_Metunknown_SampSourceunknown <- function(what = c("se", "expr", "meta")) {
  beacon_load("BLCA_BCAN_HCRN_DisTypeMIBC_NodalNo_Metunknown_SampSourceunknown", what = what)
}

#' BLCA_BCAN_HCRN_DisTypeMIBC_NodalYes_Metunknown_SampSourceunknown BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
BLCA_BCAN_HCRN_DisTypeMIBC_NodalYes_Metunknown_SampSourceunknown <- function(what = c("se", "expr", "meta")) {
  beacon_load("BLCA_BCAN_HCRN_DisTypeMIBC_NodalYes_Metunknown_SampSourceunknown", what = what)
}

#' BLCA_BCAN_HCRN_NodNeg BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
BLCA_BCAN_HCRN_NodNeg <- function(what = c("se", "expr", "meta")) {
  beacon_load("BLCA_BCAN_HCRN_NodNeg", what = what)
}

#' BLCA_BCAN_HCRN_NodPos_NeoNeg BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
BLCA_BCAN_HCRN_NodPos_NeoNeg <- function(what = c("se", "expr", "meta")) {
  beacon_load("BLCA_BCAN_HCRN_NodPos_NeoNeg", what = what)
}

#' BLCA_BCAN_HCRN_NodPos_NeoPos BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
BLCA_BCAN_HCRN_NodPos_NeoPos <- function(what = c("se", "expr", "meta")) {
  beacon_load("BLCA_BCAN_HCRN_NodPos_NeoPos", what = what)
}

#' GSE128701 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE128701 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE128701", what = what)
}

#' GSE13507 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE13507 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE13507", what = what)
}

#' GSE13507_DisTypeMIBC_NodalNo_MetNo_SampSourceCystectomy BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE13507_DisTypeMIBC_NodalNo_MetNo_SampSourceCystectomy <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE13507_DisTypeMIBC_NodalNo_MetNo_SampSourceCystectomy", what = what)
}

#' GSE13507_DisTypeNMIBC_NodalNo_MetNo_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE13507_DisTypeNMIBC_NodalNo_MetNo_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE13507_DisTypeNMIBC_NodalNo_MetNo_SampSourceTURBT", what = what)
}

#' GSE2109 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE2109 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE2109", what = what)
}

#' GSE31189 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE31189 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE31189", what = what)
}

#' GSE31684 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE31684 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE31684", what = what)
}

#' GSE31684_DisTypeMIBC_NodalNo_MetNo_SampSourceCystectomy BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE31684_DisTypeMIBC_NodalNo_MetNo_SampSourceCystectomy <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE31684_DisTypeMIBC_NodalNo_MetNo_SampSourceCystectomy", what = what)
}

#' GSE31684_DisTypeMIBC_NodalYes_MetNo_SampSourceCystectomy BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE31684_DisTypeMIBC_NodalYes_MetNo_SampSourceCystectomy <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE31684_DisTypeMIBC_NodalYes_MetNo_SampSourceCystectomy", what = what)
}

#' GSE32548 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32548 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32548", what = what)
}

#' GSE32894 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32894 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32894", what = what)
}

#' GSE32894_DisTypeMIBC_NodalNo_Metunknown_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32894_DisTypeMIBC_NodalNo_Metunknown_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32894_DisTypeMIBC_NodalNo_Metunknown_SampSourceTURBT", what = what)
}

#' GSE32894_DisTypeMIBC_Nodalunknown_Metunknown_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32894_DisTypeMIBC_Nodalunknown_Metunknown_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32894_DisTypeMIBC_Nodalunknown_Metunknown_SampSourceTURBT", what = what)
}

#' GSE32894_DisTypeMIBC_NodalYes_Metunknown_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32894_DisTypeMIBC_NodalYes_Metunknown_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32894_DisTypeMIBC_NodalYes_Metunknown_SampSourceTURBT", what = what)
}

#' GSE32894_DisTypeNMIBC_NodalNo_Metunknown_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32894_DisTypeNMIBC_NodalNo_Metunknown_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32894_DisTypeNMIBC_NodalNo_Metunknown_SampSourceTURBT", what = what)
}

#' GSE32894_DisTypeNMIBC_Nodalunknown_Metunknown_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE32894_DisTypeNMIBC_Nodalunknown_Metunknown_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE32894_DisTypeNMIBC_Nodalunknown_Metunknown_SampSourceTURBT", what = what)
}

#' GSE38264 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE38264 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE38264", what = what)
}

#' GSE48075 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE48075 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE48075", what = what)
}

#' GSE48075_DisTypeMIBC_NodalNo_MetNo_SampSourceunknown BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE48075_DisTypeMIBC_NodalNo_MetNo_SampSourceunknown <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE48075_DisTypeMIBC_NodalNo_MetNo_SampSourceunknown", what = what)
}

#' GSE48075_DisTypeMIBC_NodalYes_MetNo_SampSourceunknown BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE48075_DisTypeMIBC_NodalYes_MetNo_SampSourceunknown <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE48075_DisTypeMIBC_NodalYes_MetNo_SampSourceunknown", what = what)
}

#' GSE48075_DisTypeNMIBC_NodalNo_MetNo_SampSourceunknown BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE48075_DisTypeNMIBC_NodalNo_MetNo_SampSourceunknown <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE48075_DisTypeNMIBC_NodalNo_MetNo_SampSourceunknown", what = what)
}

#' GSE48276 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE48276 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE48276", what = what)
}

#' GSE48276_DisTypeMIBC_NodalNo_MetNo_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE48276_DisTypeMIBC_NodalNo_MetNo_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE48276_DisTypeMIBC_NodalNo_MetNo_SampSourceTURBT", what = what)
}

#' GSE52329 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE52329 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE52329", what = what)
}

#' GSE57813 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE57813 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE57813", what = what)
}

#' GSE69795 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE69795 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE69795", what = what)
}

#' GSE69795_DisTypeMIBC_NodalNo_MetNo_SampSourceTURBT BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE69795_DisTypeMIBC_NodalNo_MetNo_SampSourceTURBT <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE69795_DisTypeMIBC_NodalNo_MetNo_SampSourceTURBT", what = what)
}

#' GSE69795_DisTypeunknown_NodalNo_MetNo_SampSourceCystectomy BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE69795_DisTypeunknown_NodalNo_MetNo_SampSourceCystectomy <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE69795_DisTypeunknown_NodalNo_MetNo_SampSourceCystectomy", what = what)
}

#' GSE70691 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE70691 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE70691", what = what)
}

#' GSE70691_DisTypeMIBC_NodalNo_MetNo_SampSourceunknown BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE70691_DisTypeMIBC_NodalNo_MetNo_SampSourceunknown <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE70691_DisTypeMIBC_NodalNo_MetNo_SampSourceunknown", what = what)
}

#' GSE71576 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE71576 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE71576", what = what)
}

#' GSE83586 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE83586 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE83586", what = what)
}

#' GSE86411 BEACON study
#'
#' @param what file type selection se = standard experiment, expr = expression, meta = clinical information
#' @return
#' if what = SE, a summarized experiment
#' if what = expr: an expressino dataframe
#' if what = meta: a clinical dataframe
#'
#' @export
#'
GSE86411 <- function(what = c("se", "expr", "meta")) {
  beacon_load("GSE86411", what = what)
}

